#!/bin/bash

# Minimal /system/etc/mkshrc for Android

# Default HOSTNAME if not provided by system
: ${HOSTNAME:=$(getprop ro.product.device)}
: ${HOSTNAME:=android}
export HOSTNAME

# Default TMPDIR
: ${TMPDIR:=/tmp}
export TMPDIR

update_prompt() {
    
}

InitFox() {
    alias dir='ls -all'
    alias la='ls -a'
    alias ll='ls -a -l'
    alias lo='ls -a -l'
    alias l='find "$@" -maxdepth 1 -exec ls --color=auto -lh {} +'
    alias grep='grep -n --color=auto'
    alias fgrep='fgrep -n --color=auto'
    alias egrep='egrep -n --color=auto'
    alias python=python3
    alias python3=python_cli
    alias nano='nano --term pcansi "$@"'

    if [ -f /sdcard/Fox/fox.mkshrc ]; then
       source /sdcard/Fox/fox.mkshrc
    elif [ -f /sdcard/Fox/fox.bashrc ]; then
       source /sdcard/Fox/fox.bashrc
    elif [ -f $HOME/.mkshrc ]; then
       source $HOME/.mkshrc;
    elif [ -f /sdcard/.mkshrc ]; then
       source /sdcard/.mkshrc;
    elif [ -f /FFiles/.mkshrc ]; then
       source /FFiles/.mkshrc;
    elif [ -f /data/recovery/.mkshrc ]; then
       source /data/recovery/.mkshrc;
    elif [ -f /sdcard1/.mkshrc ]; then
       source /sdcard1/.mkshrc;
    fi
    
    [ -z "$HOME" ] && export HOME=/sdcard
    [ -z "$SHELL" ] && export SHELL=/sbin/sh
    [ -z "$LINES" ] && export LINES=34
    [ -z "$COLUMNS" ] && export COLUMNS=63
    [ -z "$TERM" ] && export TERM=pcansi
    [ -z "$IS_ORANGEFOX_USER_TERM" ] && export IS_ORANGEFOX_USER_TERM=true
    
    filcome, Enjoy this Recovery."
	echo "           <3"
    
    red=$'\x1b[01;31m'
    green=$'\x1b[01;32m'
    blue=$'\x1b[01;34m'
    purple='\[\e[35m\]'
    NC=$'\x1b[0m'
    
    if (( USER_ID )); then
   	 PS1='$'
	else
    	PS1='#'
	fi
	export PS4='[$EPOCHREALTIME] '
	local e=$?
    local new_ps1=''
    (( e )) && new_ps1+="${red}${e}${NC}|"

    new_ps1+="(${green}${HOSTNAME}${NC}:${blue}\${PWD}${NC}"
    if [ -n "$VIRTUAL_ENV" ]; then
        new_ps1+="${purple} (venv:$(basename $VIRTUAL_ENV))${NC}"
    fi

    new_ps1+=")$> "
    PS1="$new_ps1"
    return $e
}

InitFox