#!/bin/bash

# Minimal /system/etc/mkshrc for Android

# Default HOSTNAME if not provided by system
: ${HOSTNAME:=$(getprop ro.product.device)}
: ${HOSTNAME:=android}
export HOSTNAME

# Default TMPDIR
: ${TMPDIR:=/tmp}
export TMPDIR

# OrangeFox
InitFox() {
    alias dir='ls -all'
    alias la='ls -a'
    alias ll='ls -a -l'
    alias lo='ls -a -l'
    alias l='find "$@" -maxdepth 1 -exec ls --color=auto -lh {} +'
    alias grep='grep -n --color=auto'
    alias fgrep='fgrep -n --color=auto'
    alias egrep='egrep -n --color=auto'
    alias python=python3
    alias python3=python_cli
    alias nano='nano --term pansi "$@"'

    [ -z "$HOME" ] && export HOME=/sdcard
    [ -z "$SHELL" ] && export SHELL=/sbin/sh
    [ -z "$LINES" ] && export LINES=21
    [ -z "$COLUMNS" ] && export COLUMNS=44
    [ -z "$TERM" ] && export TERM=pansi
    [ -z "$IS_ORANGEFOX_USER_TERM" ] && export IS_ORANGEFOX_USER_TERM=true

    if [ -f /sdcard/Fox/fox.mkshrc ]; then
        source /sdcard/Fox/fox.mkshrc > /dev/null 2>&1
    fi

    if [ -f /sdcard/Fox/fox.bashrc ]; then
        source /sdcard/Fox/fox.bashrc > /dev/null 2>&1
    fi

    if [ -f "$HOME/.mkshrc" ]; then
        source "$HOME/.mkshrc" > /dev/null 2>&1
    elif [ -f /sdcard/.mkshrc ]; then
        source /sdcard/.mkshrc > /dev/null 2>&1
    fi
    
    if [ -f /sbin/from_fox_sd.sh ]; then
        source /sbin/from_fox_sd.sh > /dev/null 2>&1
    fi
    
    local red=$'\x1b[01;31m'
    local green=$'\x1b[01;32m'
    local blue=$'\x1b[01;34m'
    local NC=$'\x1b[0m'

    PS1='#'
    (( USER_ID )) && PS1='$'
    export PS4='[$EPOCHREALTIME] '
    export PS1="\${|
        local e=\$?
        (( e )) && REPLY+='${red}\${e}${NC}|'
        return \$e
    }${green}\${HOSTNAME}${NC}:${blue}\${PWD:-?}${NC}${PS1} "
}

InitFox

# Welcome Message
echo "Welcome, Enjoy this Recovery."
echo "           <3"

# OrangeFox