name: Recovery - Build

on:
  workflow_dispatch:
    inputs:
      BUILD_RECOVERY:
        description: 'Recovery Type'
        required: true
        default: 'OFRP'
        type: choice
        options:
          - 'OFRP'
          - 'SHRP'
          - 'TWRP'
          - 'PBRP'
      MANIFEST:
        description: 'Manifest Branch'
        required: true
        default: '12.1'
        type: choice
        options:
          - '14.1'
          - '12.1'
          - '11.3'
      DEVICE_TREE:
        description: 'Device Tree'
        required: true
        default: 'https://github.com/TDD788/A12s-DevTree'
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Branch'
        required: true
        default: 'main'
      DEVICE_PATH:
        description: 'Specify your Device Path'
        required: true
        default: 'device/samsung/a12s'
      DEVICE_NAME:
        description: 'Specify your Device Codename'
        required: true
        default: 'a12s'
      BUILD_TARGET:
        description: "Set partition to build"
        required: true
        default: 'recovery'
        type: choice
        options:
          - 'vendorboot'
          - 'boot'
          - 'recovery'
      RELEASE_TYPE:
        description: 'Normal Released Build'
        required: true
        default: true
        type: boolean
      POST_TO_TELEGRAM:
        description: 'Post to Telegram'
        required: true
        default: true
        type: boolean

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clean-up Space
      uses: rokibhasansagar/slimhub_actions@main

    - name: Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib \
        libc6-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils \
        xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libsdl1.2-dev libxml2 \
        lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static \
        libstdc++-10-dev python3 aria2 zip unzip lz4 git curl

    - name: Install Repo
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Setup Git
      run: |
        git config --global user.name "TheDarkDeath788"
        git config --global user.email "thedarkdeath788@gmail.com"

    - name: Build OrangeFox
      if: github.event.inputs.BUILD_RECOVERY == 'OFRP'
      run: |
        set +e
        mkdir -p ~/OrangeFox
        cd ~/OrangeFox
        git clone https://gitlab.com/OrangeFox/sync.git -b master --depth=1
        cd sync
        aria2c "https://github.com/TDD788/A12s-Devtree/raw/refs/heads/main/.github/orangefox_sync.sh"
        chmod +x orangefox_sync.sh
        ./orangefox_sync.sh --branch ${{ github.event.inputs.MANIFEST }} --path ~/OrangeFox/fox_${{ github.event.inputs.MANIFEST }}
        cd ~/OrangeFox/fox_${{ github.event.inputs.MANIFEST }}
        git clone ${{ github.event.inputs.DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ${{ github.event.inputs.DEVICE_PATH }} --depth=1
        echo "COMMIT_ID=$(git -C ${{ github.event.inputs.DEVICE_PATH }} rev-parse --short HEAD)" >> $GITHUB_ENV
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export BOARD_RAMDISK_USE_LZMA=true
        lunch twrp_${{ github.event.inputs.DEVICE_NAME }}-eng && mka adbd ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)
        echo "OUT_PATH=~/OrangeFox/fox_${{ github.event.inputs.MANIFEST }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}" >> $GITHUB_ENV

    - name: Build TWRP/PBRP/SHRP
      if: github.event.inputs.BUILD_RECOVERY != 'OFRP'
      run: |
        set +e
        mkdir workspace && cd workspace
        if [[ "${{ github.event.inputs.BUILD_RECOVERY }}" == "TWRP" ]]; then
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-${{ github.event.inputs.MANIFEST }}
        elif [[ "${{ github.event.inputs.BUILD_RECOVERY }}" == "PBRP" ]]; then
          repo init --depth=1 -u https://github.com/PitchBlackRecoveryProject/manifest_pb -b android-${{ github.event.inputs.MANIFEST }}
        elif [[ "${{ github.event.inputs.BUILD_RECOVERY }}" == "SHRP" ]]; then
          BRANCH="shrp-12.1"; [[ "${{ github.event.inputs.MANIFEST }}" == "11.0" ]] && BRANCH="v3_11.0"
          repo init --depth=1 -u https://github.com/SHRP-Reborn/manifest -b $BRANCH
        fi
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
        git clone ${{ github.event.inputs.DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ${{ github.event.inputs.DEVICE_PATH }} --depth=1
        echo "COMMIT_ID=$(git -C ${{ github.event.inputs.DEVICE_PATH }} rev-parse --short HEAD)" >> $GITHUB_ENV
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch twrp_${{ github.event.inputs.DEVICE_NAME }}-eng && mka adbd ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)
        echo "OUT_PATH=$(pwd)/out/target/product/${{ github.event.inputs.DEVICE_NAME }}" >> $GITHUB_ENV

    - name: Set Release Properties
      run: |
        echo "BUILD_DATE=$(TZ=Asia/Manila date +%Y%m%d)" >> $GITHUB_ENV
        cd ${{ env.OUT_PATH }}
        find . -maxdepth 1 \( -name "*.img" -o -name "*.zip" -o -name "*.tar" \) -print0 | xargs -0 md5sum > md5sums.txt
        echo "MD5_DATA<<EOF" >> $GITHUB_ENV
        cat md5sums.txt >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Upload to Release
      if: github.event.inputs.RELEASE_TYPE == 'true'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ env.OUT_PATH }}/*.img
          ${{ env.OUT_PATH }}/*.zip
          ${{ env.OUT_PATH }}/*.tar
        name: ${{ github.event.inputs.BUILD_RECOVERY }} for ${{ github.event.inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.event.inputs.BUILD_RECOVERY }}-${{ github.run_id }}
        body: |
          ## ${{ github.event.inputs.BUILD_RECOVERY }} Unofficial
          - **Build Date:** ${{ env.BUILD_DATE }}
          - **Manifest:** ${{ github.event.inputs.MANIFEST }}
          - **Device:** [Tree](${{ github.event.inputs.DEVICE_TREE }}/tree/${{ github.event.inputs.DEVICE_TREE_BRANCH }})
          - **Commit:** ${{ env.COMMIT_ID }}
          
          ### MD5 Checksums
          ```
          ${{ env.MD5_DATA }}
          ```

    - name: Post to Telegram
      if: github.event.inputs.POST_TO_TELEGRAM == 'true'
      env:
        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: |
        MESSAGE="
        <b>${{ github.event.inputs.BUILD_RECOVERY }} Build Finished</b>
        <b>Device:</b> ${{ github.event.inputs.DEVICE_NAME }}
        <b>Manifest:</b> ${{ github.event.inputs.MANIFEST }}
        <b>Commit:</b> ${{ env.COMMIT_ID }}
        <b>Download:</b> <a href=\"https://github.com/${{ github.repository }}/releases/tag/${{ github.event.inputs.BUILD_RECOVERY }}-${{ github.run_id }}\">Github Releases</a>"
        
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
        -d chat_id=${{ secrets.TELEGRAM_TO }} \
        -d parse_mode=HTML \
        -d text="${MESSAGE}"
